<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "templateresteverwertung"
 *
 * Auto generated by Extension Builder 2017-04-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'templateresteverwertung',
    'description' => 'templateresteverwertung',
    'category' => 'templates',
    'author' => 'Christine Dall',
    'author_email' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.0.0-9.15.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
