<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'BENIEDIEK\\Perfectlightbox\\' => array($typo3InstallDir . 'typo3conf/ext/perfectlightbox/Classes'),
    'DreiboxV1\\DreiboxV1\\' => array($typo3InstallDir . 'typo3conf/ext/dreibox_v1/Classes'),
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'FluidTYPO3\\Vhs\\' => array($typo3InstallDir . 'typo3conf/ext/vhs/Classes'),
    'FoT3\\Rdct\\' => array($typo3InstallDir . 'typo3conf/ext/rdct/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'IchHabRecht\\MaskExport\\' => array($typo3InstallDir . 'typo3conf/ext/mask_export/Classes'),
    'In2code\\Femanager\\' => array($typo3InstallDir . 'typo3conf/ext/femanager/Classes'),
    'JambageCom\\Div2007\\' => array($typo3InstallDir . 'typo3conf/ext/div2007/Classes'),
    'JambageCom\\TslibFetce\\' => array($typo3InstallDir . 'typo3conf/ext/tslib_fetce/Classes'),
    'MASK\\Mask\\' => array($typo3InstallDir . 'typo3conf/ext/mask/Classes'),
    'Netzmacher\\Slick\\' => array($typo3InstallDir . 'typo3conf/ext/slick/Classes'),
    'RezepteV1\\RezepteV1\\' => array($typo3InstallDir . 'typo3conf/ext/rezepte_v1/Classes'),
    'Wwagner\\Typo38videotraining\\' => array($typo3InstallDir . 'typo3conf/ext/templateresteverwertung/Classes'),
    'zweiboxV1\\ZweiboxV1\\' => array($typo3InstallDir . 'typo3conf/ext/zweibox_v1/Classes'),
);
