<?php
return [
    'BE' => [
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => '$argon2i$v=19$m=65536,t=16,p=2$N1lDUi5sTFNxR1hsd25XcA$iQZacP0oA15OUX/LLfOdeeh0ib4i06Ru3L0glP0TO+8',
        'loginSecurityLevel' => 'rsa',
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8mb4',
                'dbname' => 'server_W19042',
                'driver' => 'mysqli',
                'host' => '192.168.176.222',
                'password' => 'x2lC8wpBlo3AeRp3',
                'port' => 3306,
                'tableoptions' => [
                    'charset' => 'utf8mb4',
                    'collate' => 'utf8mb4_unicode_ci',
                ],
                'user' => 'server_W19042',
            ],
        ],
    ],
    'EXT' => [
        'extConf' => [
            'backend' => 'a:6:{s:9:"loginLogo";s:73:"fileadmin/images/logo/2614830605_568cb180-382a-47a0-975c-a953b5ecb1dc.png";s:19:"loginHighlightColor";s:7:"#257a22";s:20:"loginBackgroundImage";s:49:"fileadmin/images/Hintergrund/eat-2378726_1920.jpg";s:13:"loginFootnote";s:7:"© 2020";s:11:"backendLogo";s:73:"fileadmin/images/logo/2614830605_568cb180-382a-47a0-975c-a953b5ecb1dc.png";s:14:"backendFavicon";s:0:"";}',
            'div2007' => 'a:2:{s:6:"debug.";a:1:{s:4:"mail";s:0:"";}s:8:"dkimFile";s:0:"";}',
            'extension_builder' => 'a:3:{s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";s:15:"backupExtension";s:1:"1";s:15:"enableRoundtrip";s:1:"1";}',
            'extensionmanager' => 'a:2:{s:21:"automaticInstallation";s:1:"1";s:11:"offlineMode";s:1:"0";}',
            'femanager' => 'a:4:{s:10:"disableLog";s:1:"0";s:13:"disableModule";s:1:"0";s:24:"enableConfirmationModule";s:1:"0";s:16:"setCookieOnLogin";s:1:"0";}',
            'indexed_search' => 'a:20:{s:6:"catdoc";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:21:"enableMetaphoneSearch";s:1:"1";s:11:"flagBitMask";s:3:"192";s:18:"fullTextDataLength";s:1:"0";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:6:"minAge";s:2:"24";s:8:"pdf_mode";s:2:"20";s:8:"pdftools";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:18:"trackIpInStatistic";s:1:"2";s:5:"unrtf";s:9:"/usr/bin/";s:5:"unzip";s:9:"/usr/bin/";s:26:"useCrawlerForExternalFiles";s:1:"0";s:16:"useMysqlFulltext";s:1:"0";s:6:"xlhtml";s:9:"/usr/bin/";}',
            'mask' => 'a:9:{s:7:"backend";s:68:"typo3conf/ext/mask_project/Resources/Private/Mask/Backend/Templates/";s:18:"backendlayout_pids";s:3:"0,1";s:7:"content";s:69:"typo3conf/ext/mask_project/Resources/Private/Mask/Frontend/Templates/";s:4:"json";s:59:"typo3conf/ext/mask_project/Resources/Private/Mask/mask.json";s:7:"layouts";s:67:"typo3conf/ext/mask_project/Resources/Private/Mask/Frontend/Layouts/";s:15:"layouts_backend";s:66:"typo3conf/ext/mask_project/Resources/Private/Mask/Backend/Layouts/";s:8:"partials";s:68:"typo3conf/ext/mask_project/Resources/Private/Mask/Frontend/Partials/";s:16:"partials_backend";s:67:"typo3conf/ext/mask_project/Resources/Private/Mask/Backend/Partials/";s:7:"preview";s:49:"typo3conf/ext/mask_project/Resources/Public/Mask/";}',
            'news' => 'a:17:{s:20:"advancedMediaPreview";s:1:"1";s:11:"archiveDate";s:4:"date";s:34:"categoryBeGroupTceFormsRestriction";s:1:"0";s:19:"categoryRestriction";s:4:"none";s:21:"contentElementPreview";s:1:"1";s:22:"contentElementRelation";s:1:"1";s:19:"dateTimeNotRequired";s:1:"0";s:35:"hidePageTreeForAdministrationModule";s:1:"0";s:13:"manualSorting";s:1:"0";s:12:"mediaPreview";s:1:"0";s:13:"prependAtCopy";s:1:"1";s:22:"resourceFolderImporter";s:12:"/news_import";s:12:"rteForTeaser";s:1:"1";s:24:"showAdministrationModule";s:1:"1";s:12:"showImporter";s:1:"0";s:18:"storageUidImporter";s:1:"1";s:6:"tagPid";s:1:"1";}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'scheduler' => 'a:2:{s:11:"maxLifetime";s:4:"1440";s:15:"showSampleTasks";s:1:"1";}',
            'vhs' => 'a:1:{s:20:"disableAssetHandling";s:1:"0";}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'de',
                'fr',
                'nl',
            ],
        ],
    ],
    'EXTENSIONS' => [
        'backend' => [
            'backendFavicon' => '',
            'backendLogo' => 'fileadmin/images/logo/2614830605_568cb180-382a-47a0-975c-a953b5ecb1dc.png',
            'loginBackgroundImage' => 'fileadmin/images/Hintergrund/eat-2378726_1920.jpg',
            'loginFootnote' => '© 2020',
            'loginHighlightColor' => '#257a22',
            'loginLogo' => 'fileadmin/images/logo/2614830605_568cb180-382a-47a0-975c-a953b5ecb1dc.png',
        ],
        'div2007' => [
            'debug' => [
                'mail' => '',
            ],
            'dkimFile' => '',
        ],
        'extension_builder' => [
            'backupDir' => 'uploads/tx_extensionbuilder/backups',
            'backupExtension' => '1',
            'enableRoundtrip' => '1',
        ],
        'extensionmanager' => [
            'automaticInstallation' => '1',
            'offlineMode' => '0',
        ],
        'femanager' => [
            'disableLog' => '0',
            'disableModule' => '0',
            'enableConfirmationModule' => '0',
            'setCookieOnLogin' => '0',
        ],
        'indexed_search' => [
            'catdoc' => '/usr/bin/',
            'debugMode' => '0',
            'disableFrontendIndexing' => '0',
            'enableMetaphoneSearch' => '1',
            'flagBitMask' => '192',
            'fullTextDataLength' => '0',
            'ignoreExtensions' => '',
            'indexExternalURLs' => '0',
            'maxAge' => '0',
            'maxExternalFiles' => '5',
            'minAge' => '24',
            'pdf_mode' => '20',
            'pdftools' => '/usr/bin/',
            'ppthtml' => '/usr/bin/',
            'trackIpInStatistic' => '2',
            'unrtf' => '/usr/bin/',
            'unzip' => '/usr/bin/',
            'useCrawlerForExternalFiles' => '0',
            'useMysqlFulltext' => '0',
            'xlhtml' => '/usr/bin/',
        ],
        'mask' => [
            'backend' => 'typo3conf/ext/mask_project/Resources/Private/Mask/Backend/Templates/',
            'backendlayout_pids' => '0,1',
            'content' => 'typo3conf/ext/mask_project/Resources/Private/Mask/Frontend/Templates/',
            'json' => 'typo3conf/ext/mask_project/Resources/Private/Mask/mask.json',
            'layouts' => 'typo3conf/ext/mask_project/Resources/Private/Mask/Frontend/Layouts/',
            'layouts_backend' => 'typo3conf/ext/mask_project/Resources/Private/Mask/Backend/Layouts/',
            'partials' => 'typo3conf/ext/mask_project/Resources/Private/Mask/Frontend/Partials/',
            'partials_backend' => 'typo3conf/ext/mask_project/Resources/Private/Mask/Backend/Partials/',
            'preview' => 'typo3conf/ext/mask_project/Resources/Public/Mask/',
        ],
        'news' => [
            'advancedMediaPreview' => '1',
            'archiveDate' => 'date',
            'categoryBeGroupTceFormsRestriction' => '0',
            'categoryRestriction' => 'none',
            'contentElementPreview' => '1',
            'contentElementRelation' => '1',
            'dateTimeNotRequired' => '0',
            'hidePageTreeForAdministrationModule' => '0',
            'manualSorting' => '0',
            'mediaPreview' => '0',
            'prependAtCopy' => '1',
            'resourceFolderImporter' => '/news_import',
            'rteForTeaser' => '1',
            'showAdministrationModule' => '1',
            'showImporter' => '0',
            'storageUidImporter' => '1',
            'tagPid' => '1',
        ],
        'rsaauth' => [
            'temporaryDirectory' => '',
        ],
        'scheduler' => [
            'maxLifetime' => '1440',
            'showSampleTasks' => '1',
        ],
        'vhs' => [
            'disableAssetHandling' => '0',
        ],
    ],
    'FE' => [
        'debug' => false,
        'lifetime' => 604800,
        'loginSecurityLevel' => 'normal',
        'pageNotFound_handling' => 'true',
        'passwordHashing' => [
            'className' => 'TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\Argon2iPasswordHash',
            'options' => [],
        ],
    ],
    'GFX' => [
        'processor' => 'ImageMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'sRGB',
        'processor_effects' => true,
        'processor_enabled' => true,
        'processor_path' => '/usr/bin/',
        'processor_path_lzw' => '/usr/bin/',
    ],
    'MAIL' => [
        'transport' => 'sendmail',
        'transport_sendmail_command' => '/usr/sbin/sendmail -t -i ',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'devIPmask' => '',
        'displayErrors' => 0,
        'encryptionKey' => '721fa1b3ccf8d5477c29b2455de27cb9e749ab8908cfd243a3730c3c496211ef699b9206e505eefd36c28dfea83d8e2b',
        'exceptionalErrors' => 4096,
        'features' => [
            'unifiedPageTranslationHandling' => true,
        ],
        'sitename' => 'Resteverwertung: Die Tonne geht leer aus',
        'systemLogLevel' => 2,
        'systemMaintainers' => [
            1,
        ],
    ],
];
